-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Lun 03 Décembre 2018 à 09:32
-- Version du serveur :  5.6.17
-- Version de PHP :  5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `billetalaska`
--

-- --------------------------------------------------------

--
-- Structure de la table `posts`
--

CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `author` text NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `textresum` text NOT NULL,
  `creation_date` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=48 ;

--
-- Contenu de la table `posts`
--

INSERT INTO `posts` (`id`, `author`, `title`, `content`, `textresum`, `creation_date`) VALUES
(1, 'Jean Forteroche', 'Chapitre 1 : La décision', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed tortor et neque tempus semper. Proin vel massa ac nisi dictum blandit ac ac sem. Maecenas ultrices lacinia imperdiet. Proin nec vestibulum massa. Nullam eget mauris sollicitudin, commodo dolor nec, ornare nibh. Suspendisse sagittis lacus orci, ut finibus ligula suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse semper et lectus id molestie. Vestibulum justo ex, pharetra quis cursus pulvinar, egestas a lacus. Donec blandit odio ut massa elementum, eu consequat odio egestas. Duis nec purus vestibulum, volutpat nibh nec, lacinia neque. In justo tortor, tristique non auctor non, mattis lobortis tellus.\r\n\r\nMauris blandit mauris et euismod placerat. Nam ut risus ante. Aenean vitae diam et urna venenatis tincidunt quis eu lorem. Aliquam euismod vulputate vulputate. Nunc tempor rutrum molestie. Integer sit amet ullamcorper ligula. Morbi consectetur feugiat molestie. Mauris varius pretium auctor. Pellentesque malesuada diam mauris, vitae pretium est finibus nec. Cras vel mi metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\r\n\r\nNam placerat ullamcorper arcu, eu sodales lorem blandit a. Cras non lobortis sem, eget malesuada ipsum. Suspendisse id imperdiet risus. Nullam quis cursus felis. Vivamus euismod, odio quis euismod sagittis, magna massa accumsan nunc, ut finibus orci enim vel ipsum. Ut sed varius est, eu tristique ligula. Nunc nec mi cursus, imperdiet est eu, blandit arcu. Pellentesque pharetra dui orci, eget fringilla mi sagittis id. Donec accumsan pretium feugiat. Fusce et tortor molestie, faucibus erat quis, pulvinar est. Quisque placerat imperdiet congue.\r\n\r\nPhasellus ut nisi massa. Mauris tempor felis ac nisi vulputate, ac consequat sem efficitur. Aliquam vulputate at nisi quis malesuada. Maecenas ac venenatis purus. Nunc sapien neque, consectetur vel erat vel, sagittis sagittis lorem. Sed a luctus felis. Aenean vulputate purus tristique, eleifend risus sollicitudin, convallis massa.\r\n\r\nAenean sit amet risus id elit tempor eleifend. Etiam hendrerit mi et interdum ornare. Maecenas faucibus enim ac efficitur pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce blandit commodo magna, ut mollis massa. Aenean venenatis nisi sit amet maximus malesuada. In hac habitasse platea dictumst. Donec tempor fringilla tempor. Phasellus vitae sollicitudin nibh, facilisis vehicula est. Integer non augue eget erat commodo finibus. Fusce eu leo suscipit, elementum orci ac, posuere ipsum. Curabitur euismod massa lacus, in ultrices ligula interdum nec.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2018-11-22 11:06:41'),
(2, 'Jean Forteroche', 'Chapitre 2 : Le Conflit', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed tortor et neque tempus semper. Proin vel massa ac nisi dictum blandit ac ac sem. Maecenas ultrices lacinia imperdiet. Proin nec vestibulum massa. Nullam eget mauris sollicitudin, commodo dolor nec, ornare nibh. Suspendisse sagittis lacus orci, ut finibus ligula suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse semper et lectus id molestie. Vestibulum justo ex, pharetra quis cursus pulvinar, egestas a lacus. Donec blandit odio ut massa elementum, eu consequat odio egestas. Duis nec purus vestibulum, volutpat nibh nec, lacinia neque. In justo tortor, tristique non auctor non, mattis lobortis tellus.\r\n\r\nMauris blandit mauris et euismod placerat. Nam ut risus ante. Aenean vitae diam et urna venenatis tincidunt quis eu lorem. Aliquam euismod vulputate vulputate. Nunc tempor rutrum molestie. Integer sit amet ullamcorper ligula. Morbi consectetur feugiat molestie. Mauris varius pretium auctor. Pellentesque malesuada diam mauris, vitae pretium est finibus nec. Cras vel mi metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\r\n\r\nNam placerat ullamcorper arcu, eu sodales lorem blandit a. Cras non lobortis sem, eget malesuada ipsum. Suspendisse id imperdiet risus. Nullam quis cursus felis. Vivamus euismod, odio quis euismod sagittis, magna massa accumsan nunc, ut finibus orci enim vel ipsum. Ut sed varius est, eu tristique ligula. Nunc nec mi cursus, imperdiet est eu, blandit arcu. Pellentesque pharetra dui orci, eget fringilla mi sagittis id. Donec accumsan pretium feugiat. Fusce et tortor molestie, faucibus erat quis, pulvinar est. Quisque placerat imperdiet congue.\r\n\r\nPhasellus ut nisi massa. Mauris tempor felis ac nisi vulputate, ac consequat sem efficitur. Aliquam vulputate at nisi quis malesuada. Maecenas ac venenatis purus. Nunc sapien neque, consectetur vel erat vel, sagittis sagittis lorem. Sed a luctus felis. Aenean vulputate purus tristique, eleifend risus sollicitudin, convallis massa.\r\n\r\nAenean sit amet risus id elit tempor eleifend. Etiam hendrerit mi et interdum ornare. Maecenas faucibus enim ac efficitur pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce blandit commodo magna, ut mollis massa. Aenean venenatis nisi sit amet maximus malesuada. In hac habitasse platea dictumst. Donec tempor fringilla tempor. Phasellus vitae sollicitudin nibh, facilisis vehicula est. Integer non augue eget erat commodo finibus. Fusce eu leo suscipit, elementum orci ac, posuere ipsum. Curabitur euismod massa lacus, in ultrices ligula interdum nec.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2018-11-23 12:00:00'),
(3, 'Jean Forteroche', 'Chapitre 3 : La gare', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed tortor et neque tempus semper. Proin vel massa ac nisi dictum blandit ac ac sem. Maecenas ultrices lacinia imperdiet. Proin nec vestibulum massa. Nullam eget mauris sollicitudin, commodo dolor nec, ornare nibh. Suspendisse sagittis lacus orci, ut finibus ligula suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse semper et lectus id molestie. Vestibulum justo ex, pharetra quis cursus pulvinar, egestas a lacus. Donec blandit odio ut massa elementum, eu consequat odio egestas. Duis nec purus vestibulum, volutpat nibh nec, lacinia neque. In justo tortor, tristique non auctor non, mattis lobortis tellus.\r\n\r\nMauris blandit mauris et euismod placerat. Nam ut risus ante. Aenean vitae diam et urna venenatis tincidunt quis eu lorem. Aliquam euismod vulputate vulputate. Nunc tempor rutrum molestie. Integer sit amet ullamcorper ligula. Morbi consectetur feugiat molestie. Mauris varius pretium auctor. Pellentesque malesuada diam mauris, vitae pretium est finibus nec. Cras vel mi metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\r\n\r\nNam placerat ullamcorper arcu, eu sodales lorem blandit a. Cras non lobortis sem, eget malesuada ipsum. Suspendisse id imperdiet risus. Nullam quis cursus felis. Vivamus euismod, odio quis euismod sagittis, magna massa accumsan nunc, ut finibus orci enim vel ipsum. Ut sed varius est, eu tristique ligula. Nunc nec mi cursus, imperdiet est eu, blandit arcu. Pellentesque pharetra dui orci, eget fringilla mi sagittis id. Donec accumsan pretium feugiat. Fusce et tortor molestie, faucibus erat quis, pulvinar est. Quisque placerat imperdiet congue.\r\n\r\nPhasellus ut nisi massa. Mauris tempor felis ac nisi vulputate, ac consequat sem efficitur. Aliquam vulputate at nisi quis malesuada. Maecenas ac venenatis purus. Nunc sapien neque, consectetur vel erat vel, sagittis sagittis lorem. Sed a luctus felis. Aenean vulputate purus tristique, eleifend risus sollicitudin, convallis massa.\r\n\r\nAenean sit amet risus id elit tempor eleifend. Etiam hendrerit mi et interdum ornare. Maecenas faucibus enim ac efficitur pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce blandit commodo magna, ut mollis massa. Aenean venenatis nisi sit amet maximus malesuada. In hac habitasse platea dictumst. Donec tempor fringilla tempor. Phasellus vitae sollicitudin nibh, facilisis vehicula est. Integer non augue eget erat commodo finibus. Fusce eu leo suscipit, elementum orci ac, posuere ipsum. Curabitur euismod massa lacus, in ultrices ligula interdum nec.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2018-11-24 12:00:00'),
(4, 'Jean Forteroche', 'Chapitre 4 : Le Billet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed tortor et neque tempus semper. Proin vel massa ac nisi dictum blandit ac ac sem. Maecenas ultrices lacinia imperdiet. Proin nec vestibulum massa. Nullam eget mauris sollicitudin, commodo dolor nec, ornare nibh. Suspendisse sagittis lacus orci, ut finibus ligula suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse semper et lectus id molestie. Vestibulum justo ex, pharetra quis cursus pulvinar, egestas a lacus. Donec blandit odio ut massa elementum, eu consequat odio egestas. Duis nec purus vestibulum, volutpat nibh nec, lacinia neque. In justo tortor, tristique non auctor non, mattis lobortis tellus.\r\n\r\nMauris blandit mauris et euismod placerat. Nam ut risus ante. Aenean vitae diam et urna venenatis tincidunt quis eu lorem. Aliquam euismod vulputate vulputate. Nunc tempor rutrum molestie. Integer sit amet ullamcorper ligula. Morbi consectetur feugiat molestie. Mauris varius pretium auctor. Pellentesque malesuada diam mauris, vitae pretium est finibus nec. Cras vel mi metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\r\n\r\nNam placerat ullamcorper arcu, eu sodales lorem blandit a. Cras non lobortis sem, eget malesuada ipsum. Suspendisse id imperdiet risus. Nullam quis cursus felis. Vivamus euismod, odio quis euismod sagittis, magna massa accumsan nunc, ut finibus orci enim vel ipsum. Ut sed varius est, eu tristique ligula. Nunc nec mi cursus, imperdiet est eu, blandit arcu. Pellentesque pharetra dui orci, eget fringilla mi sagittis id. Donec accumsan pretium feugiat. Fusce et tortor molestie, faucibus erat quis, pulvinar est. Quisque placerat imperdiet congue.\r\n\r\nPhasellus ut nisi massa. Mauris tempor felis ac nisi vulputate, ac consequat sem efficitur. Aliquam vulputate at nisi quis malesuada. Maecenas ac venenatis purus. Nunc sapien neque, consectetur vel erat vel, sagittis sagittis lorem. Sed a luctus felis. Aenean vulputate purus tristique, eleifend risus sollicitudin, convallis massa.\r\n\r\nAenean sit amet risus id elit tempor eleifend. Etiam hendrerit mi et interdum ornare. Maecenas faucibus enim ac efficitur pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce blandit commodo magna, ut mollis massa. Aenean venenatis nisi sit amet maximus malesuada. In hac habitasse platea dictumst. Donec tempor fringilla tempor. Phasellus vitae sollicitudin nibh, facilisis vehicula est. Integer non augue eget erat commodo finibus. Fusce eu leo suscipit, elementum orci ac, posuere ipsum. Curabitur euismod massa lacus, in ultrices ligula interdum nec.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2018-11-26 12:00:00'),
(5, 'Jean Forteroche', 'Chapitre 5 : Le train', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed tortor et neque tempus semper. Proin vel massa ac nisi dictum blandit ac ac sem. Maecenas ultrices lacinia imperdiet. Proin nec vestibulum massa. Nullam eget mauris sollicitudin, commodo dolor nec, ornare nibh. Suspendisse sagittis lacus orci, ut finibus ligula suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse semper et lectus id molestie. Vestibulum justo ex, pharetra quis cursus pulvinar, egestas a lacus. Donec blandit odio ut massa elementum, eu consequat odio egestas. Duis nec purus vestibulum, volutpat nibh nec, lacinia neque. In justo tortor, tristique non auctor non, mattis lobortis tellus.\r\n\r\nMauris blandit mauris et euismod placerat. Nam ut risus ante. Aenean vitae diam et urna venenatis tincidunt quis eu lorem. Aliquam euismod vulputate vulputate. Nunc tempor rutrum molestie. Integer sit amet ullamcorper ligula. Morbi consectetur feugiat molestie. Mauris varius pretium auctor. Pellentesque malesuada diam mauris, vitae pretium est finibus nec. Cras vel mi metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\r\n\r\nNam placerat ullamcorper arcu, eu sodales lorem blandit a. Cras non lobortis sem, eget malesuada ipsum. Suspendisse id imperdiet risus. Nullam quis cursus felis. Vivamus euismod, odio quis euismod sagittis, magna massa accumsan nunc, ut finibus orci enim vel ipsum. Ut sed varius est, eu tristique ligula. Nunc nec mi cursus, imperdiet est eu, blandit arcu. Pellentesque pharetra dui orci, eget fringilla mi sagittis id. Donec accumsan pretium feugiat. Fusce et tortor molestie, faucibus erat quis, pulvinar est. Quisque placerat imperdiet congue.\r\n\r\nPhasellus ut nisi massa. Mauris tempor felis ac nisi vulputate, ac consequat sem efficitur. Aliquam vulputate at nisi quis malesuada. Maecenas ac venenatis purus. Nunc sapien neque, consectetur vel erat vel, sagittis sagittis lorem. Sed a luctus felis. Aenean vulputate purus tristique, eleifend risus sollicitudin, convallis massa.\r\n\r\nAenean sit amet risus id elit tempor eleifend. Etiam hendrerit mi et interdum ornare. Maecenas faucibus enim ac efficitur pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce blandit commodo magna, ut mollis massa. Aenean venenatis nisi sit amet maximus malesuada. In hac habitasse platea dictumst. Donec tempor fringilla tempor. Phasellus vitae sollicitudin nibh, facilisis vehicula est. Integer non augue eget erat commodo finibus. Fusce eu leo suscipit, elementum orci ac, posuere ipsum. Curabitur euismod massa lacus, in ultrices ligula interdum nec.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2018-11-29 12:00:00'),
(6, 'Jean Forteroche', 'Chapitre 6 : La rencontre', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed tortor et neque tempus semper. Proin vel massa ac nisi dictum blandit ac ac sem. Maecenas ultrices lacinia imperdiet. Proin nec vestibulum massa. Nullam eget mauris sollicitudin, commodo dolor nec, ornare nibh. Suspendisse sagittis lacus orci, ut finibus ligula suscipit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse semper et lectus id molestie. Vestibulum justo ex, pharetra quis cursus pulvinar, egestas a lacus. Donec blandit odio ut massa elementum, eu consequat odio egestas. Duis nec purus vestibulum, volutpat nibh nec, lacinia neque. In justo tortor, tristique non auctor non, mattis lobortis tellus. Mauris blandit mauris et euismod placerat. Nam ut risus ante. Aenean vitae diam et urna venenatis tincidunt quis eu lorem. Aliquam euismod vulputate vulputate. Nunc tempor rutrum molestie. Integer sit amet ullamcorper ligula. Morbi consectetur feugiat molestie. Mauris varius pretium auctor. Pellentesque malesuada diam mauris, vitae pretium est finibus nec. Cras vel mi metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam placerat ullamcorper arcu, eu sodales lorem blandit a. Cras non lobortis sem, eget malesuada ipsum. Suspendisse id imperdiet risus. Nullam quis cursus felis. Vivamus euismod, odio quis euismod sagittis, magna massa accumsan nunc, ut finibus orci enim vel ipsum. Ut sed varius est, eu tristique ligula. Nunc nec mi cursus, imperdiet est eu, blandit arcu. Pellentesque pharetra dui orci, eget fringilla mi sagittis id. Donec accumsan pretium feugiat. Fusce et tortor molestie, faucibus erat quis, pulvinar est. Quisque placerat imperdiet congue. Phasellus ut nisi massa. Mauris tempor felis ac nisi vulputate, ac consequat sem efficitur. Aliquam vulputate at nisi quis malesuada. Maecenas ac venenatis purus. Nunc sapien neque, consectetur vel erat vel, sagittis sagittis lorem. Sed a luctus felis. Aenean vulputate purus tristique, eleifend risus sollicitudin, convallis massa. Aenean sit amet risus id elit tempor eleifend. Etiam hendrerit mi et interdum ornare. Maecenas faucibus enim ac efficitur pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce blandit commodo magna, ut mollis massa. Aenean venenatis nisi sit amet maximus malesuada. In hac habitasse platea dictumst. Donec tempor fringilla tempor. Phasellus vitae sollicitudin nibh, facilisis vehicula est. Integer non augue eget erat commodo finibus. Fusce eu leo suscipit, elementum orci ac, posuere ipsum. Curabitur euismod massa lacus, in ultrices ligula interdum nec.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2018-12-03 09:24:00');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
